# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title IdentifyStates tries to infere cell states from a sparse Matrix and a list of example cells.
#' @aliases IdentifyStates,GeneAberExpr-method
#' @rdname IdentifyStates
#' @description Based on the example data a model for each genomic area is developed.
#' Based on these per area models the probability to be in either of these states is calculated.
#' @param X the sparse matrix (tests are applied to columns!)
#' @param range the starting points in the size distribution of the data (10!!)
#' @param interest row IDs for the group of interest
#' @param background row IDS for the background
#' @param phony print status messages (default false)
#' @return a matrix with the probabilites for each region to be in 'interest' state.
#' @export
IdentifyStates <- function(data, range, interest, background, phony) {
    .Call(`_GeneAberExpr_IdentifyStates`, data, range, interest, background, phony)
}

#' @title IdentifyStatesTest Test version of 'IdentifyStates' returing both state probabilites for the first cell.
#' @aliases IdentifyStatesTest,GeneAberExpr-method
#' @rdname IdentifyStatesTest
#' @description Based on the example data a model for each genomic area is developed.
#' Based on these per area models the probability to be in either of these states is calculated.
#' @param X the sparse matrix (tests are applied to columns!)
#' @param range the starting points in the size distribution of the data (10!!)
#' @param interest row IDs for the group of interest
#' @param background row IDS for the background
#' @param phony print status messages (default false)
#' @return a matrix with the probabilites for each region to be in 'interest' state.
#' @export
IdentifyStatesTest <- function(data, range, interest, background, phony) {
    .Call(`_GeneAberExpr_IdentifyStatesTest`, data, range, interest, background, phony)
}

#' @title GetTestModel runs sthe estimation only and returns a matrix
#' @aliases GetTestModel,GeneAberExpr-method
#' @rdname GetTestModel
#' @description Mased on the example data a model for each genomic area is developed
#' Based on these per area models the probability to be in either of these states is calculated.
#' @param X the sparse matrix (tests are applied to columns!)
#' @param range the starting points in the size distribution of the data (10!!)
#' @param interest row IDs for the group of interest
#' @param background row IDS for the background
#' @param phony print status messages (default false)
#' @return a matrix with the HMM internals (at the moment)
#' @export
GetTestModel <- function(data, range, interest, background, phony) {
    .Call(`_GeneAberExpr_GetTestModel`, data, range, interest, background, phony)
}

#' @title IceCreamTest processes the Ice cream HMM example
#' @aliases IceCreamTest,GeneAberExpr-method
#' @rdname IceCreamTest
#' @description the publication 'An Interactive Spreadsheet for Teaching the Forward-Backward Algorithm'
#' is a beatuful example of how to calculate an HMM. This function re-runs the excel data.
#' @param phony print status messages (default false)
#' @return a matrix with the HMM internals (at the moment)
#' @export
IceCreamTest <- function(phony) {
    .Call(`_GeneAberExpr_IceCreamTest`, phony)
}

#' @title goodGenes processes the Ice cream HMM example
#' @aliases goodGenes,GeneAberExpr-method
#' @rdname goodGenes
#' @description check in the sparse matrix if at least 40% of the row values are less than max
#' @return bool vector of rows with less than 40% over max columns.
#' @export
goodGenes <- function(data, max) {
    .Call(`_GeneAberExpr_goodGenes`, data, max)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_GeneAberExpr_RcppExport_registerCCallable', PACKAGE = 'GeneAberExpr')
})
